# Generated by Django 3.2.5 on 2022-05-24 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Travel place name')),
                ('describe', models.TextField(max_length=1000, verbose_name='Travel place decsribtion')),
                ('img', models.ImageField(upload_to='media', verbose_name='Travel place image')),
                ('price', models.IntegerField(verbose_name='Travel place price')),
            ],
            options={
                'verbose_name': 'Travel place name',
                'verbose_name_plural': 'Travel places names',
            },
        ),
    ]
