# Generated by Django 3.2.5 on 2022-05-24 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='index',
            options={'verbose_name': 'Travel product', 'verbose_name_plural': 'Travel products'},
        ),
    ]
