# Generated by Django 3.2.5 on 2022-05-24 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_index_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='index',
            options={'verbose_name': 'Travel place name', 'verbose_name_plural': 'Travel places names'},
        ),
    ]
