# Generated by Django 3.2.5 on 2022-05-24 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_stays'),
    ]

    operations = [
        migrations.CreateModel(
            name='fligths',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_from', models.CharField(max_length=100, verbose_name='Fligth from where the travelers comes')),
                ('flight_to', models.CharField(max_length=100, verbose_name='Flight to where they go')),
                ('img', models.ImageField(upload_to='media', verbose_name='Fligth image')),
                ('price', models.IntegerField(verbose_name='Price of the flight')),
            ],
            options={
                'verbose_name': 'Fligth',
                'verbose_name_plural': 'Flights',
            },
        ),
    ]
