# Generated by Django 3.2.5 on 2022-05-24 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_fligths'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='fligths',
            new_name='flights',
        ),
    ]
