# Generated by Django 3.2.5 on 2022-05-25 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_aboutus'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(verbose_name='The describtion of the travel place on the pages in blog part')),
                ('img', models.ImageField(upload_to='media', verbose_name='the travel place picture')),
            ],
            options={
                'verbose_name': 'travel place about',
                'verbose_name_plural': 'travel places about',
            },
        ),
    ]
