# Generated by Django 3.2.5 on 2022-05-27 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePagePicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Home Page picture part name')),
                ('about', models.TextField(verbose_name='Home page picture about')),
                ('img', models.ImageField(upload_to='media', verbose_name='Image of the home page start page')),
            ],
            options={
                'verbose_name': 'Home image',
                'verbose_name_plural': 'Home images',
            },
        ),
        migrations.CreateModel(
            name='TourIdea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Travel place name')),
                ('describe', models.TextField(max_length=1000, verbose_name='Travel place decsribtion')),
                ('img', models.ImageField(upload_to='media', verbose_name='Travel place image')),
                ('price', models.IntegerField(verbose_name='Travel place price')),
                ('in_page', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Tour idea',
                'verbose_name_plural': 'Tour ideas',
            },
        ),
        migrations.DeleteModel(
            name='index',
        ),
    ]
