# Generated by Django 3.2.5 on 2022-05-27 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20220527_1102'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Book home or house or hostel')),
                ('img', models.ImageField(upload_to='media', verbose_name='Image of cotteges or homes or hotels')),
            ],
            options={
                'verbose_name': 'Type of the accomodation',
                'verbose_name_plural': 'Types of the accomodations',
            },
        ),
        migrations.CreateModel(
            name='ProductForTours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Product name')),
                ('price', models.IntegerField(verbose_name='Price of the product')),
                ('img', models.ImageField(upload_to='media', verbose_name='product image')),
                ('price_in_page', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
