# Generated by Django 3.2.5 on 2022-05-27 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20220527_1317'),
    ]

    operations = [
        migrations.CreateModel(
            name='aboutus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(verbose_name='about our company what we giva and what we have')),
                ('img', models.ImageField(upload_to='media', verbose_name='Images of us or travel places')),
            ],
            options={
                'verbose_name': 'about us',
                'verbose_name_plural': 'about our traveling types',
            },
        ),
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(verbose_name='The describtion of the travel place on the pages in blog part')),
                ('img', models.ImageField(upload_to='media', verbose_name='the travel place picture')),
            ],
            options={
                'verbose_name': 'travel place about',
                'verbose_name_plural': 'travel places about',
            },
        ),
        migrations.CreateModel(
            name='flights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_from', models.CharField(max_length=100, verbose_name='Fligth from where the travelers comes')),
                ('flight_to', models.CharField(max_length=100, verbose_name='Flight to where they go')),
                ('img', models.ImageField(upload_to='media', verbose_name='Fligth image')),
                ('price', models.IntegerField(verbose_name='Price of the flight')),
            ],
            options={
                'verbose_name': 'Fligth',
                'verbose_name_plural': 'Flights',
            },
        ),
        migrations.CreateModel(
            name='stays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neighborhood', models.CharField(max_length=50, verbose_name='Place neighborhood')),
                ('city', models.CharField(max_length=50, verbose_name='Place city')),
                ('min_price', models.CharField(max_length=7, verbose_name='Price which will be for the staying place minimum how much')),
                ('max_price', models.CharField(max_length=7, verbose_name='Price which will be for the staying place maximum how much')),
                ('property_status', models.CharField(max_length=50, verbose_name='Property status what will be')),
                ('property_type', models.CharField(max_length=50, verbose_name='Property type what will be')),
                ('BHK', models.CharField(max_length=50, verbose_name='BHK')),
                ('aminities', models.CharField(max_length=50, verbose_name='what we want to have in our hotel or hostel')),
                ('bedroom', models.CharField(max_length=10, verbose_name='How much bedrooms')),
                ('bathroom', models.CharField(max_length=10, verbose_name='How many bathrooms')),
            ],
            options={
                'verbose_name': 'Stay',
                'verbose_name_plural': 'Stays',
            },
        ),
    ]
