# Generated by Django 3.2.5 on 2022-05-28 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_aboutus_blog_flights_stays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touridea',
            name='describe',
            field=models.TextField(max_length=500, verbose_name='Travel place decsribtion'),
        ),
        migrations.AlterField(
            model_name='touridea',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Travel place name'),
        ),
    ]
