# Generated by Django 3.2.5 on 2022-06-11 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
