# Generated by Django 3.2.5 on 2022-06-11 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_delete_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, verbose_name='Product name')),
                ('decsribe', models.TextField(blank=True, verbose_name='Product describtion')),
                ('price', models.IntegerField(blank=True, verbose_name='Product price')),
                ('img', models.ImageField(blank=True, upload_to='media', verbose_name='Product image')),
            ],
            options={
                'verbose_name': 'HomeProduct',
                'verbose_name_plural': 'HomeProducts',
            },
        ),
        migrations.CreateModel(
            name='HomeSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='slide  name')),
                ('about', models.TextField(max_length=2000, verbose_name='slide about')),
                ('image', models.ImageField(upload_to='media', verbose_name='slide  image')),
            ],
            options={
                'verbose_name': 'tour',
                'verbose_name_plural': 'tours',
            },
        ),
        migrations.DeleteModel(
            name='BookingStayPlace',
        ),
        migrations.DeleteModel(
            name='HomePagePicture',
        ),
        migrations.DeleteModel(
            name='OurServices',
        ),
        migrations.DeleteModel(
            name='ProductForTours',
        ),
        migrations.DeleteModel(
            name='TourIdea',
        ),
        migrations.DeleteModel(
            name='TourPlace',
        ),
        migrations.AlterModelOptions(
            name='flights',
            options={'verbose_name': 'Flight', 'verbose_name_plural': 'Flights'},
        ),
        migrations.RemoveField(
            model_name='flights',
            name='flight_from',
        ),
        migrations.RemoveField(
            model_name='flights',
            name='flight_to',
        ),
        migrations.AddField(
            model_name='flights',
            name='flights_from',
            field=models.CharField(blank=True, max_length=100, verbose_name='Flight from where the travelers comes'),
        ),
        migrations.AddField(
            model_name='flights',
            name='flights_to',
            field=models.CharField(blank=True, max_length=100, verbose_name='Flight to where they go'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='about',
            field=models.TextField(blank=True, verbose_name='about our company what we giva and what we have'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='img',
            field=models.ImageField(blank=True, upload_to='media', verbose_name='Images of us or travel places'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='about',
            field=models.TextField(blank=True, verbose_name='The describtion of the travel place on the pages in blog part'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='img',
            field=models.ImageField(blank=True, upload_to='media', verbose_name='the travel place picture'),
        ),
        migrations.AlterField(
            model_name='flights',
            name='img',
            field=models.ImageField(blank=True, upload_to='media', verbose_name='Flight image'),
        ),
        migrations.AlterField(
            model_name='flights',
            name='price',
            field=models.IntegerField(blank=True, verbose_name='Price of the flight'),
        ),
        migrations.AlterField(
            model_name='stays',
            name='BHK',
            field=models.CharField(blank=True, max_length=50, verbose_name='BHK'),
        ),
        migrations.AlterField(
            model_name='stays',
            name='aminities',
            field=models.CharField(blank=True, max_length=50, verbose_name='what we want to have in our hotel or hostel'),
        ),
        migrations.AlterField(
            model_name='stays',
            name='bathroom',
            field=models.CharField(blank=True, max_length=50, verbose_name='How many bathrooms'),
        ),
        migrations.AlterField(
            model_name='stays',
            name='bedroom',
            field=models.CharField(blank=True, max_length=50, verbose_name='How much bedrooms'),
        ),
        migrations.AlterField(
            model_name='stays',
            name='city',
            field=models.CharField(blank=True, max_length=50, verbose_name='Place city'),
        ),
        migrations.AlterField(
            model_name='stays',
            name='max_price',
            field=models.CharField(blank=True, max_length=50, verbose_name='Price which will be for the staying place maximum how much'),
        ),
        migrations.AlterField(
            model_name='stays',
            name='min_price',
            field=models.CharField(blank=True, max_length=50, verbose_name='Price which will be for the staying place minimum how much'),
        ),
        migrations.AlterField(
            model_name='stays',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=50, verbose_name='Place neighborhood'),
        ),
        migrations.AlterField(
            model_name='stays',
            name='property_status',
            field=models.CharField(blank=True, max_length=50, verbose_name='Property status what will be'),
        ),
        migrations.AlterField(
            model_name='stays',
            name='property_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='Property type what will be'),
        ),
    ]
