# Generated by Django 3.2.5 on 2022-06-11 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20220611_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='name',
            field=models.CharField(blank=True, max_length=3000, verbose_name='About page name'),
        ),
    ]
