# Generated by Django 3.2.5 on 2022-06-12 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_cart_usercarts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homeslide',
            options={'verbose_name': 'Slide', 'verbose_name_plural': 'Slides'},
        ),
    ]
